import React from "react";
import "./Scrolling_banner_section.css";

function Partners() {
  return (
      <div id="partners_section">
        <article className="wrapper">
          <div className="marquee">
            <div className="marquee_group">
              <img
                src="https://www.vectorlogo.zone/logos/python/python-horizontal.svg"
                alt="python"
              />
              <img
                src="https://www.vectorlogo.zone/logos/r-project/r-project-ar21.svg"
                alt="R-project"
              />
              <img
                src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-ar21.svg"
                alt="tensorflow"
              />
              <img
                src="https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg"
                alt="pytorch"
              />
              <img
                src="https://streamlit.io/images/brand/streamlit-logo-secondary-colormark-darktext.svg"
                alt="react"
              />
              <img
                src="https://www.vectorlogo.zone/logos/reactjs/reactjs-ar21.svg"
                alt="react"
              />
              <img
                src="https://www.vectorlogo.zone/logos/json/json-ar21.svg"
                alt="json"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg"
                alt="spark"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png"
                alt="databricks"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"
                alt="SQL"
              />
              <img
                src="https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-ar21.svg"
                alt="AWS"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/4/45/Logo_OVH.svg"
                alt="OVH"
              />
              <img
                src="https://logos-world.net/wp-content/uploads/2021/05/Microsoft-Azure-Logo.png"
                alt="azure"
              />
              <img
                src="https://www.vectorlogo.zone/logos/microsoft_powerbi/microsoft_powerbi-ar21.svg"
                alt="Power BI"
              />
              <img
                src="https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png"
                alt="MySQL"
              />
            </div>

            <div aria-hidden="true" className="marquee_group">
              <img
                  src="https://www.vectorlogo.zone/logos/python/python-horizontal.svg"
                  alt="python"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/r-project/r-project-ar21.svg"
                  alt="R-project"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-ar21.svg"
                  alt="tensorflow"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg"
                  alt="pytorch"
                />
                <img
                  src="https://streamlit.io/images/brand/streamlit-logo-secondary-colormark-darktext.svg"
                  alt="react"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/reactjs/reactjs-ar21.svg"
                  alt="react"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/json/json-ar21.svg"
                  alt="json"
                />
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg"
                  alt="spark"
                />
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png"
                  alt="databricks"
                />     
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"
                  alt="SQL"
                />           
                <img
                  src="https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-ar21.svg"
                  alt="AWS"
                />
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/4/45/Logo_OVH.svg"
                  alt="OVH"
                />
                <img
                  src="https://logos-world.net/wp-content/uploads/2021/05/Microsoft-Azure-Logo.png"
                  alt="azure"
                />
                <img
                  src="https://www.vectorlogo.zone/logos/microsoft_powerbi/microsoft_powerbi-ar21.svg"
                  alt="Power BI"
                />
                <img
                  src="https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png"
                  alt="MySQL"
                />
            </div>
          </div>

          {/* <div className="marquee marquee_reverse">
            <div className="marquee_group">
              <img
                src="https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png"
                alt="MySQL"
              />
              <img
                src="https://www.vectorlogo.zone/logos/microsoft_powerbi/microsoft_powerbi-ar21.svg"
                alt="Power BI"
              /> 
              <img
                src="https://logos-world.net/wp-content/uploads/2021/05/Microsoft-Azure-Logo.png"
                alt="azure"
              />             
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/4/45/Logo_OVH.svg"
                alt="OVH"
              />
              <img
                src="https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-ar21.svg"
                alt="AWS"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"
                alt="SQL"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png"
                alt="databricks" 
              />              
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg"
                alt="spark"
              />
              <img
                src="https://www.vectorlogo.zone/logos/json/json-ar21.svg"
                alt="json"
              />
              <img
                src="https://www.vectorlogo.zone/logos/reactjs/reactjs-ar21.svg"
                alt="react"
              />
              <img
                src="https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg"
                alt="pytorch"
              />
              <img
                src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-ar21.svg"
                alt="tensorflow"
              />
              <img
                src="https://www.vectorlogo.zone/logos/r-project/r-project-ar21.svg"
                alt="R-project"
              />
              <img
                src="https://www.vectorlogo.zone/logos/python/python-horizontal.svg"
                alt="python"
              />
            </div>

            <div aria-hidden="true" className="marquee_group">
              <img
                src="https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png"
                alt="MySQL"
              />
              <img
                src="https://www.vectorlogo.zone/logos/microsoft_powerbi/microsoft_powerbi-ar21.svg"
                alt="Power BI"
              />
              <img
                src="https://logos-world.net/wp-content/uploads/2021/05/Microsoft-Azure-Logo.png"
                alt="azure"
              />
              <img
                  src="https://upload.wikimedia.org/wikipedia/commons/4/45/Logo_OVH.svg"
                  alt="OVH"
              />
              <img
                src="https://www.vectorlogo.zone/logos/amazon_aws/amazon_aws-ar21.svg"
                alt="AWS"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/8/87/Sql_data_base_with_logo.png"
                alt="SQL"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png"
                alt="databricks"
              />
              <img
                src="https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg"
                alt="spark"
              />
              <img
                src="https://www.vectorlogo.zone/logos/json/json-ar21.svg"
                alt="json"
              />
              <img
                src="https://www.vectorlogo.zone/logos/reactjs/reactjs-ar21.svg"
                alt="react"
              />
              <img
                src="https://www.vectorlogo.zone/logos/pytorch/pytorch-ar21.svg"
                alt="pytorch"
              />
              <img
                src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-ar21.svg"
                alt="tensorflow"
              />
              <img
                src="https://www.vectorlogo.zone/logos/r-project/r-project-ar21.svg"
                alt="R-project"
              />
              <img
                src="https://www.vectorlogo.zone/logos/python/python-horizontal.svg"
                alt="python"
              />
            </div>
          </div> */}
        </article>
      </div>
  );
}

export default Partners;
